package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"
	"graphql-server/configs"
	"graphql-server/graph/model"
)

var (
	db = configs.ConnectDB()
)

// CreateData is the resolver for the createData field.
func (r *mutationResolver) CreateData(ctx context.Context, input model.NewData) (*model.Data, error) {
	data, err := db.CreateData(&input)
	return data, err
}

// Data is the resolver for the data field.
func (r *queryResolver) Data(ctx context.Context) ([]*model.Data, error) {
	dataList, err := db.GetDataList()
	return dataList, err
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
